export default () => {
  return {
    minicourses: [
      [ // Bloco A
        'Invasões Biológicas',
        'Introdução aos Métodos de estudo em Anatomia Comparativa de Vertebrados',
        'Citogenética Animal',
        'Cultivo de células em Mamíferos',
        'Insetos e o homem: vamos discutir esta relação?',
        'Imunoterapias',
        'Produção de Biofármacos',
        'O despertar dos sentidos: o que sentimos, por que sentimos e como sentimos?',
        'Oficina de Iniciação em Bonsai',
        'Desenvolvimento e Aplicação de Nanopartículas Carreadoras de Fármacos',
      ], [ // Bloco B
        'Aprendendo a aprender',
        'Programação de Computadores para Estudantes de Biologia',
        'Introdução à Biologia Subterrânea',
        'O imperador de todos os males: Câncer',
        'Genética Forense',
        'O Mundo das Plantas Carnívoras',
        'Sexualidade e Gênero na Educação',
        'Biologia de Parasitoides',
        'Biologia de Cetáceos',
        'Seleção Sexual',
      ], [ // Bloco C
        'Vida underground: o que podemos aprender com os solos?',
        'Divulgação e Comunicação Científica',
        'Novas metodologias para Ensino',
        'Biologia e Criação de Abelhas Sem Ferrão',
        'Embriões de Peixe-Zebra como modelo emergente em Ecotoxicologia',
        'Organismos aquáticos e a relação destes com a Qualidade Ambiental',
        'Restauração e Conservação do Cerrado',
        'Tartarugas Marinhas',
        'Teratologia',
        'Amazônia e Cerrado: Ecofisiologia de Espécies Arbóreas',
      ], [ // Bloco D
        'Cavalos-Marinhos: o que são e por quê protegê-los?',
        'Biologia Forense Animal: contribuições da academia na resolução de crimes contra a fauna',
        'Paleontologia: introdução ao estado da arte',
        'Interação Planta-Praga',
        'Visualização e simulação de proteínas',
        'O conhecimento da hereditariedade: da domesticação de plantas e animais à herança epigenética',
        'Introdução à Proteômica: técnicas e aplicações',
        'Venenos animais',
        'Segredos de professor: técnicas didáticas em sala de aula',
        'Ecologia e História Natural de serpentes e outros répteis brasileiros',
      ], [ // Bloco E
        'Biomas do Brasil',
        'Projeto de Filmagem de Vida Silvestre',
        'PaleoArte',
        'Vulnerabilidade Animal Frente às Mudanças Climáticas',
      ]
    ],
    lectures: [
      'A Odisseia da Vida',
      'Optogenética - Controlando o cérebro com a luz',
      'Como nossa alimentação pode salvar o mundo?',
      'Microbiologia e o Avanço da Medicina',
      'Medicinas tradicionais do povo indígena Puyanawa',
      'Impactos do Ecoturismo',
      'Evolução do Medo',
      'Etnobotânica',
      'Propriedade Intelectual',
      'Os eventos de extinção: a sexta grande extinção',
      'Ciência em Quadrinhos',
    ],
    talkingCircles: [
      'Revolução na Educação',
      'Me formei. E agora?',
      'Crise Hídrica',
      'Mulheres na Ciência',
    ]
  }
}
