export default () => ({
  'SEG': [
    { time:'08:00', name: 'Minicursos Bloco A'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Palestra'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos Bloco C'},
  ],
  'TER': [
    { time:'08:00', name: 'Minicursos Bloco A'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra'},
    { time:'14:30', name: 'Palestra'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Palestra'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos Bloco C'},
  ],
  'QUA': [
    { time:'08:00', name: 'Minicursos Bloco B'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra'},
    { time:'14:30', name: 'Palestra'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos Bloco D'},
  ],
  'QUI': [
    { time:'08:00', name: 'Minicursos Bloco B'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra'},
    { time:'14:30', name: 'Palestra'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos Bloco D'},
  ],
  'SEX': [
    { time:'08:00', name: 'Minicursos Bloco E'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra'},
    { time:'14:30', name: 'Palestra de Encerramento'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Roda da Conversa'},
    { },
    { },
  ],
  'SAB': [
    { time:'08:00', name: 'Congratulações'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Festa de Despedida'},
  ],
})
