export default () => ({
  'SEG': [
    { time:'08:00', names: ['Minicursos Bloco A', 'Entrega de kits']},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'A Odisseia da Vida'},
    { time:'14:30', name: 'Impactos do Ecoturismo'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Ciência em Quadrinhos'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:30', name: 'Minicursos Bloco B'},
  ],
  'TER': [
    { time:'08:00', name: 'Minicursos Bloco A'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Optogenética - Controlando o cérebro com a luz'},
    { time:'14:30', name: 'Evolução do Medo'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Revolução na Educação'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:30', name: 'Minicursos Bloco B'},
  ],
  'QUA': [
    { time:'08:00', name: 'Minicursos Bloco C'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Como nossa alimentação pode salvar o mundo?'},
    { time:'14:30', name: 'Etnobotânica'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Me formei. E agora?'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:30', name: 'Minicursos Bloco D'},
  ],
  'QUI': [
    { time:'08:00', name: 'Minicursos Bloco C'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Microbiologia e o Avanço da Medicina'},
    { time:'14:30', name: 'Propriedade Intelectual'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Crise Hídrica'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:30', name: 'Minicursos Bloco D'},
  ],
  'SEX': [
    { time:'08:00', name: 'Minicursos Bloco E'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Medicinas tradicionais do povo indígena Puyanawa'},
    { time:'14:30', name: 'Os eventos de extinção: a sexta grande extinção'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:15', name: 'Mulheres na Ciência'},
    {},{},
  ],
  'SAB': [
    {
      time:'08:00',
      names: [
        'Minicursos Bloco E',
        'Workshops: Projeto Fauna UnB',
        'Exposições: Bio na Rua',
        'Projeto Sala de Ciência',
      ]
    },
    { time:'11:30', name: 'A Biologia em Nossa Vida'},
    {},{},{},{},{},{},
  ],
})
