export default {
  'SEG': [
    { time:'08:00', name: 'Minicursos Bloco A'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra sobre Robertos'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:00', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos Bloco B'},
  ],
  'TER': [
    { time:'08:00', name: 'Congratulações'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra sobre Abacates'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:00', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos sobre blocos'},
  ],
  'QUA': [
    { time:'08:00', name: 'Congratulações'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra sobre Abacates'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:00', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos sobre blocos'},
  ],
  'QUI': [
    { time:'08:00', name: 'Congratulações'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra sobre Jurupinga'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:00', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Minicursos sobre blocos'},
  ],
  'SEX': [
    { time:'08:00', name: 'Congratulações'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra sobre Robertos'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:00', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Despedida'},
  ],
  'SAB': [
    { time:'08:00', name: 'Congratulações'},
    { time:'11:30', name: 'Almoço'},
    { time:'13:00', name: 'Palestra de Abertura'},
    { time:'14:30', name: 'Palestra sobre Robertos'},
    { time:'15:45', name: 'Coffee Break'},
    { time:'16:00', name: 'Roda da Conversa'},
    { time:'17:30', name: 'Jantar'},
    { time:'19:00 às 22:00', name: 'Festa de Despedida'},
  ],
}
